### ISSUE TITLE
sziko

### ISSUE THREAD

**Issue by Freedomwhi** [rdp-studio/pro.rdpstudio.top#1]
- [x] 我已知晓并确保我的网站不会“无内容”，详见js.org协议

请务必保管好申请ISSUE申请帖地址！取消注册时会用到。

请在下方填写网站解析记录，最多三条(格式：解析方式 解析内容 TTL)：

**Comment by rdp-studio** [comment]
没有解析创建什么域名。。。

**Comment by rdp-studio** [comment]
还有请用新版https://github.com/rdp-studio/thedevid.rdpstudio.top
